"""State-only catch-up: 0009 added read_at without the help_text the model
carries, so every HOST running makemigrations --check failed with a phantom
AlterField it could not write into site-packages. No schema change - help_text
lives only in migration state."""
# Generated by Django on 2026-09-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_notificationlog_read_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='read_at',
            field=models.DateTimeField(blank=True, help_text="When the recipient marked this feed row read (POST feed/read/). NULL means unread, and unread is the only state a feed row is born in — the column is about the RECIPIENT's attention, not about delivery, which `status` already records. Only push rows are ever read: those are the ones GET feed/ returns.", null=True),
        ),
    ]
