# Generated by Django 6.0.8 on 2026-09-19 10:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_notificationlog_device_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkedDispatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('log_id', models.UUIDField(help_text="The NotificationLog row that recorded the skip. The retry's idempotency key: replaying deletes this row and flips that one, in one transaction.", unique=True)),
                ('user_id', models.UUIDField(db_index=True)),
                ('notification_type', models.CharField(db_index=True, max_length=50)),
                ('channel', models.CharField(max_length=10)),
                ('event_id', models.CharField(blank=True, default='', max_length=255)),
                ('language', models.CharField(blank=True, default='', max_length=5)),
                ('request', models.JSONField(default=dict, help_text='The process_notification arguments, verbatim — variables included, which is why this model is declared secret and why the type allowlist is narrow. Never rendered into a log line.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Parked Dispatch',
                'verbose_name_plural': 'Parked Dispatches',
                'indexes': [models.Index(fields=['created_at', 'notification_type'], name='notificatio_created_cae580_idx')],
            },
        ),
    ]
